-- Supabase SQL Editorで実行してください。
create table if not exists public.futsal_goods (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  video_id text not null,
  good_time integer not null default 0,
  description text not null,
  user_name text,
  comment text
);

alter table public.futsal_goods enable row level security;

create policy "public can read futsal goods"
on public.futsal_goods for select
to anon using (true);

create policy "public can insert futsal goods"
on public.futsal_goods for insert
to anon with check (true);

drop policy if exists "public can delete futsal goods" on public.futsal_goods;
create policy "public can delete futsal goods"
on public.futsal_goods for delete
to anon using (true);

create index if not exists futsal_goods_video_id_idx
on public.futsal_goods(video_id);
